# Generated by Django 3.2.3 on 2022-02-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sale_sold_or_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, to='api.item'),
        ),
    ]
