# Generated by Django 3.2.3 on 2022-02-08 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item', to_field='item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item', to_field='item'),
        ),
    ]
